/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;


import accesoADatos.HorariosData;
import accesoADatos.RutasData;
import entidades.Horarios;
import entidades.Rutas;
import java.awt.Color;
import java.awt.Dimension;
import java.time.LocalTime;
import java.util.ArrayList;
import java.util.List;

import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Cristian
 */
public class BusquedaHorarios extends javax.swing.JInternalFrame {
    RutasData ruData = new RutasData();
    HorariosData horarioData = new HorariosData();
    List<Horarios> listadoHorariosXID;
    List<Rutas> listaRutas;
    List<Horarios> listadoHorarios;
    List<Horarios> listaXhora;
    List<Horarios> listaXhorayRuta;
    
    private DefaultTableModel modeloTabla = new DefaultTableModel(){
        public boolean isCellEditable(int i, int i1) {

            return false;

        }
    };

    public BusquedaHorarios() {
        initComponents();
        armarCabecera();
        ocultarBarraTitulo();
        listaRutas = ruData.listarRutas();
        listadoHorarios = horarioData.listarHorarios();
        llenarTablas();
        llenarComboRuta();
        llenarComboHoraSalida();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCSeleccionRuta = new javax.swing.JComboBox<>();
        jCHoraSalida = new javax.swing.JComboBox<>();
        jLimpiar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jBuscar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTHorarios = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setBorder(null);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Seleccionar una ruta:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Horario de salida:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jCSeleccionRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCSeleccionRutaActionPerformed(evt);
            }
        });
        jPanel3.add(jCSeleccionRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 260, -1));

        jCHoraSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCHoraSalidaActionPerformed(evt);
            }
        });
        jPanel3.add(jCHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 260, -1));

        jLimpiar.setBackground(new java.awt.Color(138, 193, 223));
        jLimpiar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLimpiar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jLimpiarMouseMoved(evt);
            }
        });
        jLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLimpiarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLimpiarMouseExited(evt);
            }
        });
        jLimpiar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/limpiar2.png"))); // NOI18N
        jLabel7.setText("Limpiar");
        jLimpiar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        jPanel3.add(jLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 130, 30));

        jBuscar.setBackground(new java.awt.Color(138, 193, 223));
        jBuscar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jBuscar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jBuscarMouseMoved(evt);
            }
        });
        jBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBuscarMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBuscarMouseExited(evt);
            }
        });
        jBuscar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        jLabel9.setText("Buscar");
        jBuscar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 30));

        jPanel3.add(jBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 130, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 630, 180));

        jTHorarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Salida", "Llegada", "Ruta"
            }
        ));
        jScrollPane1.setViewportView(jTHorarios);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 650, 320));

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Busqueda de Horarios");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 190, 40));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 40));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLimpiarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLimpiarMouseMoved
        jLimpiar.setBackground(new Color(184, 210, 224));
    }//GEN-LAST:event_jLimpiarMouseMoved

    private void jLimpiarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLimpiarMouseExited
        jLimpiar.setBackground(new Color(138, 193, 223));
    }//GEN-LAST:event_jLimpiarMouseExited

    private void jCSeleccionRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCSeleccionRutaActionPerformed
        // TODO add your handling code here:
        borrarComboBoxHoras();
    }//GEN-LAST:event_jCSeleccionRutaActionPerformed

    private void jLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLimpiarMouseClicked
        // TODO add your handling code here:
        llenarComboHoraSalida();
        llenarTablas();
    }//GEN-LAST:event_jLimpiarMouseClicked

    private void jBuscarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuscarMouseMoved
        // TODO add your handling code here:
        jBuscar.setBackground(new Color(184, 210, 224));
    }//GEN-LAST:event_jBuscarMouseMoved

    private void jBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuscarMouseClicked
        // TODO add your handling code here:
        if (jCHoraSalida.getSelectedIndex() == (-1)) {
            Rutas i = (Rutas) jCSeleccionRuta.getSelectedItem();
            listadoHorariosXID = horarioData.listarHorariosXRuta(i.getIdRuta());
            llenarComboHoraSalidaXRuta();
            buscarTabla();
        } else if (jCSeleccionRuta.getSelectedIndex() == -1) {
            Horarios h = (Horarios) jCHoraSalida.getSelectedItem();
            listaXhora = horarioData.listarHorariosXSalida(h.getHoraSalida());
            llenarTablaHorarios();
        } else {
            Rutas i = (Rutas) jCSeleccionRuta.getSelectedItem();
            Horarios h = (Horarios) jCHoraSalida.getSelectedItem();
            listaXhorayRuta = horarioData.listarHorariosDoble(i.getIdRuta(), h.getHoraSalida());
            llenarTablaDoble();
        }
        
    }//GEN-LAST:event_jBuscarMouseClicked

    private void jBuscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBuscarMouseExited
        // TODO add your handling code here:
        jBuscar.setBackground(new Color(138, 193, 223));
    }//GEN-LAST:event_jBuscarMouseExited

    private void jCHoraSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCHoraSalidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCHoraSalidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jBuscar;
    private javax.swing.JComboBox<Horarios> jCHoraSalida;
    private javax.swing.JComboBox<Rutas> jCSeleccionRuta;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jLimpiar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTHorarios;
    // End of variables declaration//GEN-END:variables
    
    
    public void ocultarBarraTitulo() {
        JComponent Barra = null;
        Dimension dimBarra = null;
        Barra = ((BasicInternalFrameUI) getUI()).getNorthPane();
        dimBarra = Barra.getPreferredSize();
        Barra.setSize(0, 0);
        Barra.setPreferredSize(new Dimension(0, 0));
        repaint();
    }
    
    private void armarCabecera() {        
        modeloTabla.addColumn("Salida");
        modeloTabla.addColumn("Llegada");
        modeloTabla.addColumn("Ruta");
        jTHorarios.setModel(modeloTabla);
    }
    
    private void llenarTablas(){
        borrarFilas();
        for (Horarios x : listadoHorarios) {
                modeloTabla.addRow(new Object[]{x.getHoraSalida(), x.getHoraLLegada(), x.getRuta()});
        }
    }
        
    public void buscarTabla(){
        borrarFilas();
        for (Horarios x : listadoHorariosXID) {
                modeloTabla.addRow(new Object[]{x.getHoraSalida(), x.getHoraLLegada(), x.getRuta()});
        }
            
    }   
    
    private void llenarTablaHorarios(){
        borrarFilas();
        for (Horarios x : listaXhora) {
                modeloTabla.addRow(new Object[]{x.getHoraSalida(), x.getHoraLLegada(), x.getRuta()});
        } 
        
    }
    
    private void llenarTablaDoble(){
        borrarFilas();
        for (Horarios x : listaXhorayRuta) {
                modeloTabla.addRow(new Object[]{x.getHoraSalida(), x.getHoraLLegada(), x.getRuta()});
        } 
    }

    public void llenarComboRuta(){
        for (Rutas e : listaRutas) {
            jCSeleccionRuta.addItem(e); 
        }
        
        jCSeleccionRuta.setSelectedIndex(-1);
    }
    
    public void llenarComboHoraSalida(){
        borrarComboBox();
        for (Horarios s : listadoHorarios) {
            jCHoraSalida.addItem(s);
        }
        jCHoraSalida.setSelectedIndex(-1);
    }
    
    public void llenarComboHoraSalidaXRuta(){
        borrarComboBoxHoras();
        for (Horarios s : listadoHorariosXID) {
            jCHoraSalida.addItem(s);
        }
        jCHoraSalida.setSelectedIndex(-1);
    }
    

    private void borrarFilas() {
        int filas = modeloTabla.getRowCount() - 1;
        for (int f = filas; f >= 0; f--) {
            modeloTabla.removeRow(f);
        }
    }
    
    private void borrarComboBox(){
        jCSeleccionRuta.setSelectedIndex(-1);
        jCHoraSalida.setSelectedIndex(-1);
        
    }
    
    private void borrarComboBoxHoras(){
        jCHoraSalida.removeAllItems();
    }
    

    
}
